### ISSUE TITLE
[BUG] Pipeline multistream se salta detecciones

### ISSUE THREAD

**Issue by pgallardor** [alercebroker/pipeline#270]

**Comment by pgallardor** [comment]
A dia de hoy, este bug es obra de un maguito

**Comment by dirodriguezm** [comment]
-   Maguito
    encontré al maguito 🧙‍♂️. Prv candidates no limpaba los fp_hists ni prv_candidates así que quedaban mensajes muy grandes
    
        ### prv candidates step ztf strategy
        def extract_detections_and_non_detections(alert: dict) -> dict:
            prv_candidates = alert["extra_fields"].pop("prv_candidates")
            prv_candidates = pickle.loads(prv_candidates) if prv_candidates else []
            forced_photometries = alert["extra_fields"].pop("fp_hists", [])
            forced_photometries = (
                pickle.loads(forced_photometries) if forced_photometries else []
            )
            acopy = alert.copy()
            detections = [acopy]
            non_detections = []
        
            detections = detections + [
                ZTFPreviousDetectionsParser.parse_message(candidate, alert)
                for candidate in prv_candidates
                if ZTFPreviousDetectionsParser.can_parse(candidate)
            ]
            non_detections = [
                ZTFNonDetectionsParser.parse_message(candidate, alert)
                for candidate in prv_candidates
                if ZTFNonDetectionsParser.can_parse(candidate)
            ]
            alert["extra_fields"]["parent_candid"] = None
            detections = detections + [
                ZTFForcedPhotometryParser.parse_message(fp, alert)
                for fp in forced_photometries
                if ZTFForcedPhotometryParser.can_parse(fp)
            ]
        
            return {
                "aid": alert["aid"],
                "detections": detections,
                "non_detections": non_detections,
            }
    
    Los mensajes muy grandes no lanzaban error porque el productor realmente no lanza el error. Estaba 100% asíncrono, es decir, nunca esperaba ningúna confirmación por lo que esos mensajes fallidos se perdían y mientras el step siguiera funcionando, no se enteraba que el productor falló
    
    Una solución es hacer flush al final de cada batch. A continuación una posible implementación:
    
        #### kafka producer
        def produce(self, message=None, **kwargs):
            """Produce Message to a topic.
        
            Parameters
            ----------
            message: dict | None
                The value of the message to be produced.
                Should match the schema defined in the config["SCHEMA"]
        
            **kwargs: dict
                Any other keyword argument will be passed as **kwargs to the produce method of the producer.
                Do not specify the key argument, as it will be duplicated.
        
            NOTE: To set a key for the message, use the set_key_field(key_field) method prior to consuming
            The producer will have a key_field attribute that will be either None, or some specified value,
            and will use that for each produce() call.
            """
        
            def acked(err, msg):
                self.logger.debug("Message produced")
                if err is not None:
                    if isinstance(err, BufferError):
                        self.logger.error(f"Error producing message: {err}")
                        self.logger.error("Calling poll to empty queue and producing again")
                        self.producer.flush(1)
                        self.producer.produce(
                            topic, value=msg, key=key, callback=acked, **kwargs
                        )
                    else:
                        raise err
        
            key = None
            if message:
                key = message[self.key_field] if self.key_field else None
            message = self._serialize_message(message)
            if self.dynamic_topic:
                self.topic = self.topic_strategy.get_topics()
            for topic in self.topic:
                flush = kwargs.pop("flush", False)
                self.producer.produce(
                    topic, value=message, key=key, callback=acked, **kwargs
                )
                if flush:
                    self.producer.flush(1)
    
    Y por el lado del step hay que indicarle al producer cuándo hacer flush
    
        #### apf step
        def produce(self, result: Union[List[Dict[str, Any]], Dict[str, Any]]):
            """
            Produces messages using the configured producer class.
        
            Parameters
            ----------
            result: dict | list[dict]
                The result of the step's execution.
                This parameter can be an iterable or a single message, where the message should be
                a dictionary that matches the output schema of the step.
        
            NOTE: If you want to produce with a key, use the set_producer_key_field(key_field)
            method somewhere in the lifecycle of the step prior to the produce state.
            """
            if isinstance(result, dict):
                to_produce = [result]
            else:
                to_produce = result
            count = 0
            for prod_message in to_produce:
                count += 1
                flush = count == len(to_produce)
                self.producer.produce(prod_message, flush=flush)
            if not isinstance(self.producer, DefaultProducer):
                self.logger.info(f"Produced {len(to_produce)} messages")
