### ISSUE TITLE
Probar alerce_classifiers como submodulo manteniendo el repo privado

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#29]
Sería ideal poder tener un flujo en el que lc_classification_step pueda instalar localmente alerce_classifiers, desarrollar ambos paquetes de forma local y que evolucionen en conjunto, mientras el repo de alerce_classifiers se mantiene privado.

Ejemplo:

1. Clonar pipeline
2. Clonar submodulo
3. Desarrollar step + alerce_classifiers
4. Pushear pipeline + submodule alerce_classifiers
6. CI corre test + actualiza versión de step
7. CI corre test + actualiza versión de alerce_classifiers
   Este ambiente de CI sería el de pipeline solamente. Debería hacer clone de pipeline + submodulo
8. CI pushea nueva versión de pipeline y de alerce_classifiers

**Comment by HectorxH** [comment]
PR:
- https://github.com/alercebroker/alerce_classifiers/pull/32
- https://github.com/alercebroker/pipeline/pull/58
