### ISSUE TITLE
[Sorting Hat] [Performance] Cambiar parsers a dict en lugar de dataclasses

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#292]
![Image](https://github.com/alercebroker/pipeline/assets/18015991/21b20cc0-3f7f-49a2-84d9-11000c2926e0)

**Comment by pgallardor** [comment]
Esto ya estaba a medio hacer, ahora veamos si pasarle diccionarios en lugar de dataclasses soluciona el problema de performance
