### ISSUE TITLE
Debug clasificación Balto

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#295]

**Comment by Bastiancito88** [comment]
Bug detectado en la creacion del dataframe de deteciones, en este se esta realizando un drop 
de duplciados a nivel de id (aid), esto genera que las series sean truncadas a una sola deteccion (medicion)


[https://github.com/alercebroker/pipeline/blob/main/lc_classification_step/lc_classification/core/parsers/input_dto.py](url)

la seccion a cambiar es la siguiente

`detections = [
        pd.DataFrame.from_records(msg["detections"]) for msg in messages
    ]
    detections = pd.concat(detections)
    detections.drop_duplicates("candid", inplace=True)
    detections = detections.set_index("aid")
    detections["extra_fields"] = parse_extra_fields(detections)`


cambiando la linea de drop, quedando el siguiente bloque de codigo :


`detections = [
        pd.DataFrame.from_records(msg["detections"]) for msg in messages
    ]
    detections = pd.concat(detections)
    detections.drop_duplicates("candid", inplace=True)
    detections = detections.set_index("aid")
    detections["extra_fields"] = parse_extra_fields(detections)`
