### ISSUE TITLE
[BUG] Meanra y meandec no incluye todas las detecciones

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#339]
Parece que está usando solo las detecciones de mongo

**Comment by ale-munozarancibia** [comment]
Ejemplo: [ZTF23abutifi ](https://alerce.online/object/ZTF23abutifi)q tiene aid=AL23kmvkuaclpldzk (único oid asociado a ese aid) tiene 8 detecciones, y según el explorer todas tienen stamp salvo 1. Pero en postgres sólo aparecen 2 detecciones con has_stamp=True, mismas detecciones q son las únicas escritas en mongodb

**Comment by ale-munozarancibia** [comment]
Más ejemplos: [ZTF21abhjygu](https://alerce.online/object/ZTF21abhjygu), [ZTF20acvgboc](https://alerce.online/object/ZTF20acvgboc), [ZTF23abutifi](https://alerce.online/object/ZTF23abutifi) (mismo de comentario anterior) y [ZTF23aaabegx](https://alerce.online/object/ZTF23aaabegx), para ellos meanra y meandec q obtuve post fix de ayer a https://github.com/alercebroker/pipeline/issues/337 son consistentes con escoger de postgres sólo detecciones q tengan has_stamp=True y mjd>60282 (o sea post cambio de pipeline). Notar q ZTF23abutifi y ZTF23aaabegx son objetos nuevos así q el total de sus detecciones tienen mjd>60282

**Comment by ale-munozarancibia** [comment]
Aquí otro ejemplo de mismatch entre stamps de explorer y detection/prv_candidate en postgres: mirando la curva desde noviembre de [ZTF20acuutku](https://alerce.online/object/ZTF20acuutku), según el explorer tiene prv_candidates en 13 nov y 6 dec (sin stamp). En postgres ambas filas tienen has_stamp=False (candids 2507323314615010030 y 2530219293415010040, mjds 60261.3 y 60284.2) y eso está bien, pero hay varias detecciones de noviembre q tb tienen has_stamp=False y stamps a la vez (ver sus demás detecciones en postgres con mjd>60249). Notar q este objeto en mongodb comparte aid con [ZTF18abcxmal](https://alerce.online/object/ZTF18abcxmal).

Este objeto (o más bien su aid) pasó por el lc classifier post fix de ayer a #337. Antes del fix no había pasado por el lc classifier en la nueva pipeline.
