### ISSUE TITLE
Mejorar logging de LC Classification Step

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#64]
- [x] Tarea1: Crear Logs
- [x] Tarea2: Warning missing diaObject

### Tarea  1 corta

Logger cosas como (level DEBUG):

- mensajes de entrada
- describir el inputDTO
  - cantidad de detecciones
  - cuales detecciones son prv candidates, cuales son forced photometry
  - cantidad de features
- describir el outputDTO
  - distribución de las clases
- describir updates de scribe
  - lista de objetos y la operación

### Tarea 2 corta

Checkear todos los mensajes, guardar una lista de los aid de cada mensaje que cumpla con la condicion de warning (prv candidate or forced true y falta campo diaObject). 

Duda: un aid pueder ser al mismo tiempo prv candidate y forced?

Generar 1 warnig con dos mensajes, uno para los prv candidate y uno para los forced? O un mensaje con "estos aid fallaron porque falta diaObject)

level WARNING
- prv candidates o forced photometry sin `extra_fields.diaObject` (caso elasticc)

**Comment by ASHuenchuleo** [comment]
Cree una rama para la tarea 1 con un primer intento, pero no se me ocurre bien como testearlo aún de una manera simple.
