### ISSUE TITLE
Agregar APF

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#8]
Depende de alercebroker/pipeline#10

**Comment by HectorxH** [comment]
## Steps en los que funciona APF local
- [ ] Alert Archiving Step
	- Error building `fastavro`
- [x] Correction Step
- [ ] Early Classification Step
	- Step requires Python >=3.7, <3.8
	- apf-base requires Python >=3.8
- [ ] Feature Step `*`
- [ ] Lightcurve Classification step
	- `TypeError: __init__() got an unexpected keyword argument 'level'`
- [x] Lightcurve Step
- [x] Magstats Step
- [x] Prv Candidates Step
- [ ] Reflector Step
	- Error building `fastavro`
- [ ] S3 Step `*`
- [x] Scribe
- [x] Sorting Hat Step
- [ ] Stamp Classifier Step `*`
- [ ] Watchlist Step
	- `TypeError: __init__() got an unexpected keyword argument 'level'`
- [ ] XMatch Step
	- Step requires Python >=3.7, <3.8
	- apf-base requires Python >=3.8

`*`: No los logre hacer que los test me funcionaran localmente antes de siquiera utilizar el apf local
