### ISSUE TITLE
Consumir log stream desde cloudwatch en grafana

### ISSUE THREAD

**Issue by AlxEnashi** [alercebroker/pipeline#83]
Los logs de cloudwach se deben poder explorar desde gafana. Con la finalidad de tener toda la informaicon para monitorear la pipeline en el mismo lugar.

- [x] Agregar input desde cloudwatch en grafana. (esto probablemente implica reconocer los indices o diferentes streams en cloudwatch en grafana)

### Para consumir desde cloudwatch
- [x] Crear usuario para grafana
- [x] Darle permisos de cloudwatch (politica)
- [x] Crear DataSource en grafana 
- [ ] Crear el Dashboard

### Criterio de aceptacion
Se pueden ver los logs de cloudwatch en un dashboard de grafana con opciones de busqueda.

Problema con esta solucion. Idealmente se debe poder usar el rol del cluster para acceder a cloudwatch sin tener que manejar credenciales solo para esta tarea.

EDIT 22 sept: solo hace falta asignarle correctamente el rol a los node groups. Luego grafana es capaz de usar el rol de la instancia del cluster para acceder a cloudwatch.

**Comment by dirodriguezm** [comment]
Quedó mas o menos avanzado. Los logs ahora mismo necesitan tags o algo para poder diferenciar a qué aplicación o proyecto pertenecen (ej: cual step, o si es de pipeline o de servicio web).

Avance actual:  https://github.com/alercebroker/infrastructure_provisioning/commit/84e2fdbe765560ed851431d0d15d7cc1a6da4456

**Comment by dirodriguezm** [comment]
Este PR https://github.com/alercebroker/pipeline/pull/166 agrega la funcionalidad para los steps de la pipeline de usar las labels de kubernetes como campo `source` en Elasticsearch. Todavía falta hacer la modificación en el dashboard de Grafana
