### ISSUE TITLE
Refactorizar create_input_dto para funcionar desde correction

### ISSUE THREAD

**Issue by AlxEnashi** [alercebroker/pipeline#91]
En lc_classification_step/lc_classification/core/parsers/input_dto.py
```python
def create_features_dto(messages: List[dict]) -> pd.DataFrame:
    # el aid y el features se puede obtener en una sola lectura de la lista de mensajes.
    df = pd.DataFrame([{"aid": message.get("aid")} for message in messages])
    features = pd.DataFrame(
        [for message imessage["features"] n messages if message["features"]]
    )
    features["aid"] = df.aid
    # todo lo que esta entre los comentarios ^^ puede ser 1 linea
    features.drop_duplicates("aid", inplace=True)
    features = features.set_index("aid")
    if features is not None:
        return features
    else:
        raise ValueError("Could not set index aid on features dataframe")
``` 

### Tareas
- [x] Hacer el cambio de la creacion del dataframe de features en create_features_dto
- [x] Asegurarse que si no hay campo features en los mensajes no se caiga (capturar el key error o un get)
- [x] si para algun aid no existe la llave feature en el mensaje, ese aid no va en el dataframe final

### Criterio de aceptacion
- [x] Revisar si hay test para create_input_dto que cubra el caso en que no hay nignu feature y el caso en que vienen todos los features
- [x] Si no existe crearlo, si existe estamos listo mientras pase el test.

**Comment by ASHuenchuleo** [comment]
Está establecio en el ejemplo que aids se pueden repetir. Si llega un aid1 con features, y luego uno sin nada, no tiene sentido retroactivaemente borrar los datos anteriores o si=

**Comment by dirodriguezm** [comment]
Si el aid llega con features al menos una vez, después van a seguir llegando con al menos las mismas features o con nuevos cálculos.
