### ISSUE TITLE
Mergear ZTF con el nuevo diseño del step

### ISSUE THREAD

**Issue by AlxEnashi** [alercebroker/pipeline#94]
### Tareas

- [ ] Agregar el caso ztf a select_model e instanciarlo en el init del step
- [ ] Agregar caso especial en el execute para sacar del input_dto solo los features y pasar ese input al ztf model
- [ ] En lc_classification_step/lc_classification/predictors/ztf_random_forest/ztf_random_forest_parser.py to_parse es el resultado de la clasificacion. Se debe crear una funcion que transforme el diccionario a un outputdto. Y crear el caso especial para que se use.
- [ ] Refactorizar lc_classification_step/lc_classification/core/parsers/alerce_parser.py para usar input_dto como input y output dto como probabilidades.

**Comment by dirodriguezm** [comment]
Idea de implementación



![Image](https://github.com/alercebroker/pipeline/assets/18015991/27bffba5-ce2a-48e6-9862-4a1d568033b7)
